apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  namespace: website
spec:
  ingressClassName: traefik
  rules:
    - host: aebi-nicola.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
      http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80